export const REQUEST_GET_MOVIES = 'REQUEST_GET_MOVIES';
export const RECEIVE_GET_MOVIES = 'RECEIVE_GET_MOVIES';
export const UPDTE_SEARCH_WORD = 'UPDTE_SEARCH_WORD';
export const UPDTE_SEARCH_TYPE = 'UPDTE_SEARCH_TYPE';
export const UPDTE_SEARCH_YEAR = 'UPDTE_SEARCH_YEAR';
